import type { Question } from "@shared/schema";

export const questions: Question[] = [
  {
    id: "color-preference",
    text: "Which is your color preference? (Select all that apply.)",
    options: [
      {
        id: "black-and-white",
        text: "Black and White",
        color: "#5A7FCA",
        trait: "conscientiousness",
        score: 0.8,
      },
      {
        id: "earthy-neutrals",
        text: "Earthy Neutrals, Gray",
        color: "#7DB5A6",
        trait: "agreeableness",
        score: 0.7,
      },
      {
        id: "pastels-pale",
        text: "Pastels and Pale Colors",
        color: "#4A6FBA",
        trait: "neuroticism",
        score: -0.6,
      },
      {
        id: "bright-colors",
        text: "Bright Colors",
        color: "#6DA596",
        trait: "extraversion",
        score: 0.9,
      },
      {
        id: "shiny-metallics",
        text: "Shiny Metallics",
        color: "#7DB5A6",
        trait: "openness",
        score: 0.8,
      },
    ],
  },
  {
    id: "social-activity",
    text: "In social situations, you prefer to:",
    options: [
      {
        id: "lead-conversation",
        text: "Lead the Conversation",
        color: "#5A7FCA",
        trait: "extraversion",
        score: 0.9,
      },
      {
        id: "listen-observe",
        text: "Listen and Observe",
        color: "#7DB5A6",
        trait: "introversion",
        score: -0.7,
      },
      {
        id: "contribute-when-asked",
        text: "Contribute When Asked",
        color: "#4A6FBA",
        trait: "agreeableness",
        score: 0.6,
      },
      {
        id: "avoid-attention",
        text: "Avoid Attention",
        color: "#6DA596",
        trait: "neuroticism",
        score: 0.7,
      },
      {
        id: "share-unique-perspectives",
        text: "Share Unique Perspectives",
        color: "#7DB5A6",
        trait: "openness",
        score: 0.8,
      },
    ],
  },
  {
    id: "work-style",
    text: "Your ideal work environment is:",
    options: [
      {
        id: "structured-routine",
        text: "Structured with Routine",
        color: "#5A7FCA",
        trait: "conscientiousness",
        score: 0.9,
      },
      {
        id: "collaborative-team",
        text: "Collaborative Team",
        color: "#7DB5A6",
        trait: "agreeableness",
        score: 0.8,
      },
      {
        id: "flexible-creative",
        text: "Flexible and Creative",
        color: "#4A6FBA",
        trait: "openness",
        score: 0.9,
      },
      {
        id: "fast-paced-dynamic",
        text: "Fast-Paced and Dynamic",
        color: "#6DA596",
        trait: "extraversion",
        score: 0.7,
      },
      {
        id: "calm-predictable",
        text: "Calm and Predictable",
        color: "#7DB5A6",
        trait: "neuroticism",
        score: -0.8,
      },
    ],
  },
  {
    id: "decision-making",
    text: "When making important decisions, you:",
    options: [
      {
        id: "analyze-thoroughly",
        text: "Analyze Thoroughly",
        color: "#5A7FCA",
        trait: "conscientiousness",
        score: 0.8,
      },
      {
        id: "seek-others-input",
        text: "Seek Others' Input",
        color: "#7DB5A6",
        trait: "agreeableness",
        score: 0.7,
      },
      {
        id: "trust-intuition",
        text: "Trust Your Intuition",
        color: "#4A6FBA",
        trait: "openness",
        score: 0.6,
      },
      {
        id: "decide-quickly",
        text: "Decide Quickly",
        color: "#6DA596",
        trait: "extraversion",
        score: 0.7,
      },
      {
        id: "worry-about-consequences",
        text: "Worry About Consequences",
        color: "#7DB5A6",
        trait: "neuroticism",
        score: 0.8,
      },
    ],
  },
  {
    id: "stress-response",
    text: "When facing stress, you typically:",
    options: [
      {
        id: "create-detailed-plan",
        text: "Create a Detailed Plan",
        color: "#5A7FCA",
        trait: "conscientiousness",
        score: 0.8,
      },
      {
        id: "seek-support",
        text: "Seek Support from Others",
        color: "#7DB5A6",
        trait: "agreeableness",
        score: 0.6,
      },
      {
        id: "try-new-approaches",
        text: "Try New Approaches",
        color: "#4A6FBA",
        trait: "openness",
        score: 0.7,
      },
      {
        id: "take-immediate-action",
        text: "Take Immediate Action",
        color: "#6DA596",
        trait: "extraversion",
        score: 0.8,
      },
      {
        id: "feel-overwhelmed",
        text: "Feel Overwhelmed",
        color: "#7DB5A6",
        trait: "neuroticism",
        score: 0.9,
      },
    ],
  },
];
