import type { Question } from "@shared/schema";

export const questions: Question[] = [
  {
    id: "color-preference",
    text: "Which is your color preference? (Select all that apply.)",
    options: [
      {
        id: "black-and-white",
        text: "BLACK AND WHITE",
        color: "#5A7FCA",
        trait: "conscientiousness",
        score: 0.8,
      },
      {
        id: "earthy-neutrals",
        text: "EARTHY NEUTRALS, GRAY",
        color: "#7DB5A6",
        trait: "agreeableness",
        score: 0.7,
      },
      {
        id: "pastels-pale",
        text: "PASTELS AND PALE COLORS",
        color: "#4A6FBA",
        trait: "neuroticism",
        score: -0.6,
      },
      {
        id: "bright-colors",
        text: "BRIGHT COLORS",
        color: "#6DA596",
        trait: "extraversion",
        score: 0.9,
      },
      {
        id: "shiny-metallics",
        text: "SHINY METALLICS",
        color: "#7DB5A6",
        trait: "openness",
        score: 0.8,
      },
    ],
  },
  {
    id: "social-activity",
    text: "In social situations, you prefer to:",
    options: [
      {
        id: "lead-conversation",
        text: "LEAD THE CONVERSATION",
        color: "#5A7FCA",
        trait: "extraversion",
        score: 0.9,
      },
      {
        id: "listen-observe",
        text: "LISTEN AND OBSERVE",
        color: "#7DB5A6",
        trait: "introversion",
        score: -0.7,
      },
      {
        id: "contribute-when-asked",
        text: "CONTRIBUTE WHEN ASKED",
        color: "#4A6FBA",
        trait: "agreeableness",
        score: 0.6,
      },
      {
        id: "avoid-attention",
        text: "AVOID ATTENTION",
        color: "#6DA596",
        trait: "neuroticism",
        score: 0.7,
      },
      {
        id: "share-unique-perspectives",
        text: "SHARE UNIQUE PERSPECTIVES",
        color: "#7DB5A6",
        trait: "openness",
        score: 0.8,
      },
    ],
  },
  {
    id: "work-style",
    text: "Your ideal work environment is:",
    options: [
      {
        id: "structured-routine",
        text: "STRUCTURED WITH ROUTINE",
        color: "#5A7FCA",
        trait: "conscientiousness",
        score: 0.9,
      },
      {
        id: "collaborative-team",
        text: "COLLABORATIVE TEAM",
        color: "#7DB5A6",
        trait: "agreeableness",
        score: 0.8,
      },
      {
        id: "flexible-creative",
        text: "FLEXIBLE AND CREATIVE",
        color: "#4A6FBA",
        trait: "openness",
        score: 0.9,
      },
      {
        id: "fast-paced-dynamic",
        text: "FAST-PACED AND DYNAMIC",
        color: "#6DA596",
        trait: "extraversion",
        score: 0.7,
      },
      {
        id: "calm-predictable",
        text: "CALM AND PREDICTABLE",
        color: "#7DB5A6",
        trait: "neuroticism",
        score: -0.8,
      },
    ],
  },
  {
    id: "decision-making",
    text: "When making important decisions, you:",
    options: [
      {
        id: "analyze-thoroughly",
        text: "ANALYZE THOROUGHLY",
        color: "#5A7FCA",
        trait: "conscientiousness",
        score: 0.8,
      },
      {
        id: "seek-others-input",
        text: "SEEK OTHERS' INPUT",
        color: "#7DB5A6",
        trait: "agreeableness",
        score: 0.7,
      },
      {
        id: "trust-intuition",
        text: "TRUST YOUR INTUITION",
        color: "#4A6FBA",
        trait: "openness",
        score: 0.6,
      },
      {
        id: "decide-quickly",
        text: "DECIDE QUICKLY",
        color: "#6DA596",
        trait: "extraversion",
        score: 0.7,
      },
      {
        id: "worry-about-consequences",
        text: "WORRY ABOUT CONSEQUENCES",
        color: "#7DB5A6",
        trait: "neuroticism",
        score: 0.8,
      },
    ],
  },
  {
    id: "stress-response",
    text: "When facing stress, you typically:",
    options: [
      {
        id: "create-detailed-plan",
        text: "CREATE A DETAILED PLAN",
        color: "#5A7FCA",
        trait: "conscientiousness",
        score: 0.8,
      },
      {
        id: "seek-support",
        text: "SEEK SUPPORT FROM OTHERS",
        color: "#7DB5A6",
        trait: "agreeableness",
        score: 0.6,
      },
      {
        id: "try-new-approaches",
        text: "TRY NEW APPROACHES",
        color: "#4A6FBA",
        trait: "openness",
        score: 0.7,
      },
      {
        id: "take-immediate-action",
        text: "TAKE IMMEDIATE ACTION",
        color: "#6DA596",
        trait: "extraversion",
        score: 0.8,
      },
      {
        id: "feel-overwhelmed",
        text: "FEEL OVERWHELMED",
        color: "#7DB5A6",
        trait: "neuroticism",
        score: 0.9,
      },
    ],
  },
];
